language: java
jdk:
  - oraclejdk8

#cache:
#  directories:
#  - $HOME/.m2

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
    app: ruscigno-chronos